---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: likes
  namespace: opa-talk
  labels:
    app.kubernetes.io/name: likes
  annotations:
    traefik.ingress.kubernetes.io/rule-type: Path
spec:
  tls:
  - hosts:
    - example.com
    secretName: tls-cert
  rules:
  - host: api.example.com
    http:
      paths:
      - path: /users/{userId}/likes
        backend:
          serviceName: likes
          servicePort: http