---
kind: ConfigMap
apiVersion: v1
metadata:
  name: opa-configuration
  namespace: opa-talk
  labels:
    app.kubernetes.io/name: middleman
data:
  config.yml: |
    services:
    - name: s3
      url: https://opa-talk.s3.amazonaws.com/
    bundle:
      name: bundle.tar.gz
      service: s3
      prefix: /
      polling:
        min_delay_seconds: 5
        max_delay_seconds: 15
